version: '3.8'
services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./db/Dockerfile
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    container_name: app
    build:
      context: ./app
    env_file:
      - .env
    depends_on:
      - db